### ISSUE TITLE
"pydot" github organization

### ISSUE THREAD

**Issue by prmtl** [pydot/pydot#139]
Hello! I have a https://github.com/pydot organization created for the purpose of creating pydot-ng. Now since pydot was resurrected I think that you might make a better use of that organization. Will you be interested in transferring this organization to you as a (possible) new place for pydot repo?

**Comment by johnyf** [comment]
Thanks for suggesting this. I would be good with that (`pydot/pydot`, as is the case with `networkx`, `scipy`, `numpy`, etc.). However, the repository's owner is @erocarrera (the author of `pydot`), so it would be his decision (I can commit here and release on PyPI, but I cannot move the repository).

**Comment by prmtl** [comment]
Any updates on that? :)

CC: @erocarrera

**Comment by prmtl** [comment]
I just wanted to link https://github.com/pydot/pydot-ng/pull/52#issuecomment-438914445 where discussion about moving to `pydot` organisation is happening.

**Comment by prmtl** [comment]
And `pydot/pydot` has landed!
