### ISSUE TITLE
how to directly pass on pydot graph to graphviz

### ISSUE THREAD

**Issue by parthi2929** [pydot/pydot#173]
Hi

I want to pass on networkx graph object to graphviz. Currently doing via pydot. However, I unnecessarily have to write an intermediatory file as below

```
P = nx.nx_pydot.to_pydot(G)
nx.nx_pydot.write_dot(G,'test.dot')                 # write to dot file
(graph,) = pydot.graph_from_dot_file('test.dot')    # read to dot file
print(graph)
```

It would be great if I need not write and read file, and instead directly pass on from pydot to graphviz. Can you please let me know how? There are no documentation so unable to find.

**Comment by johnyf** [comment]
The variable `P` is a `pydot` graph, one way to confirm this is `type(P)`, and to see a representation in DOT, `str(P)`. Indeed, user guide and tutorial documentation for `pydot` are under construction #130. The docstrings can be viewed with the [`help` function](https://docs.python.org/3/library/functions.html#help) (or [`?` in `ipython`](https://ipython.org/ipython-doc/3/interactive/reference.html#dynamic-object-information)).

**Comment by parthi2929** [comment]
yeah, so how do I transform pydot Graph to Graphviz object without having to write a file as above?

**Comment by johnyf** [comment]
The interface from `pydot` to GraphViz uses files. A DOT representation without calling GraphViz can be obtained with `str`.

**Comment by parthi2929** [comment]
Great, str(P) worked.
