### ISSUE TITLE
Error in error handling hides the real error message

### ISSUE THREAD

**Issue by shish** [pydot/pydot#176]
https://github.com/erocarrera/pydot/blob/d6ac9e9244d1a882103422ac2b35ceef96f5dfe3/dot_parser.py#L554

probably want `str(err)`, not just `err`? Currently I am getting

```
pydot raised an error: must be str, not ParseException
```

When I would expect to be getting?

```
pydot raised an error: Expected "}" (at char 688), (line:19, col:29)
```

**Comment by peternowee** [comment]
Thanks for reporting. I submitted a PR to fix this: https://github.com/pydot/pydot/pull/219.
