### ISSUE TITLE
Error in installing pydot on google colab

### ISSUE THREAD

**Issue by Hemantr05** [pydot/pydot#188]
I tried installing pydot in order to visualize my model but gave me this error:

ImportError: Failed to import `pydot`. Please install `pydot`. For example with `pip install pydot`

Even after pip install pydot or rather, !pip install pydot on google colab

**Comment by Hemantr05** [comment]
Now, it works.

Thanks :D

**Comment by prmtl** [comment]
Didn't do anything but I'm happy it works :)
