### ISSUE TITLE
Reading custom attributes in a node

### ISSUE THREAD

**Issue by pratapan9** [pydot/pydot#212]
I have dot graph string like

> digraph "new_graph" {
>   "Graph_ID_1" [label="My graph" schema="my_schema" page=2];
> }
>   

I know I can use node.get_name() or node.get_label() to read name/label.

what methods in the library can I use to read the custom properties like 'schema' or 'page' in the above case?

**Comment by peternowee** [comment]
Hi @pratapan9, thanks for your question and sorry it did not get any response earlier. I think this is a duplicate of pydot/pydot#151. I just added an answer there that should also answer your question. Please leave any further questions or comments there. Thanks!
