### ISSUE TITLE
Error while running Pydot in Python 3 on  Mac

### ISSUE THREAD

**Issue by thomasvengal** [pydot/pydot#232]
Using Jupyter Notebook 6.0.3 on Macbook.
pydot==1.4.1
pydotplus==2.0.2

When I run the code below:

_import pydot
G = nx.complete_graph(4)
pos = nx.nx_pydot.graphviz_layout(G)
pos = nx.nx_pydot.graphviz_layout(G, prog='dot')_

I am getting the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-d2e13af6fd7a> in <module>
----> 1 pos = nx.nx_pydot.pydot_layout(G)

~/opt/anaconda3/lib/python3.7/site-packages/networkx/drawing/nx_pydot.py in pydot_layout(G, prog, root)
    307 
    308     """
--> 309     import pydot
    310     P = to_pydot(G)
    311     if root is not None:

~/Google Drive/BITS-DSE/3-Graphs-Algorithms-Mining/Assignment-5/pydot.py in <module>
      2 G = nx.complete_graph(4)
      3 
----> 4 pos = nx.nx_pydot.pydot_layout(G)
      5 pos = nx.nx_pydot.pydot_layout(G, prog='neato')

~/opt/anaconda3/lib/python3.7/site-packages/networkx/drawing/nx_pydot.py in pydot_layout(G, prog, root)
    308     """
    309     import pydot
--> 310     P = to_pydot(G)
    311     if root is not None:
    312         P.set("root", make_str(root))

~/opt/anaconda3/lib/python3.7/site-packages/networkx/drawing/nx_pydot.py in to_pydot(N)
    201     graph_defaults = N.graph.get('graph', {})
    202     if name == '':
--> 203         P = pydot.Dot('', graph_type=graph_type, strict=strict,
    204                       **graph_defaults)
    205     else:

**AttributeError: module 'pydot' has no attribute 'Dot'**

**Comment by peternowee** [comment]
Not sure if I am seeing this right, but could it be that `import pydot` in line 309 accidentally does not import the real pydot library, but instead imports your own script again that also happens to be named `pydot.py`?

Maybe try renaming `~/Google Drive/BITS-DSE/3-Graphs-Algorithms-Mining/Assignment-5/pydot.py` to something like `myscript.py`.

And please format program output as code, btw. See https://guides.github.com/features/mastering-markdown/

**Comment by peternowee** [comment]
Since there was no further reply, I assume this issue has been resolved and I will close it now. Feel free to reopen it if necessary.

**Comment by NeuralFlux** [comment]
> Not sure if I am seeing this right, but could it be that `import pydot` in line 309 accidentally does not import the real pydot library, but instead imports your own script again that also happens to be named `pydot.py`?
> 
> Maybe try renaming `~/Google Drive/BITS-DSE/3-Graphs-Algorithms-Mining/Assignment-5/pydot.py` to something like `myscript.py`.
> 
> And please format program output as code, btw. See https://guides.github.com/features/mastering-markdown/

In a similar way, I had unintentionally named my Python script as "dot_parser.py" and it seemed to overwrite one of the pydot imports. Just changing the name solved my issue!
