### ISSUE TITLE
Can't call graphviz in Windows OS

### ISSUE THREAD

**Issue by shakedbr** [pydot/pydot#244]
Hi,

In `call_graphviz(...)` function, there is a call to `subprocess.Popen` .
According to the [documentation](https://docs.python.org/3.7/library/subprocess.html#subprocess.Popen) of  `subprocess.Popen`,  
"If specified, _env_ must provide any variables required for the program to execute. On Windows, in order to run a side-by-side assembly the specified env **must** include a valid `SystemRoot`."

The current implementation of `call_graphviz(...)` doesn't handle this issue and therefore failed to work on Windows environment.

I suggest the following change in `call_graphviz(...)` (in `pydot.py`):
```
def call_graphviz(program, arguments, working_dir, **kwargs):
   ...
    env = {
        'PATH': os.environ.get('PATH', ''),
        'LD_LIBRARY_PATH': os.environ.get('LD_LIBRARY_PATH', ''),
    }

    if is_windows():
        env['SYSTEMROOT'] = os.environ.get('SYSTEMROOT', '') 
   ...
```

Best,
Shaked

**Comment by peternowee** [comment]
Hi Shaked, thanks for reporting this! I have actually been waiting for a confirmation like this for PR pydot/pydot#208, so very happy to finally see one come in! Perhaps you can reply there and then we can close this issue as duplicate.

**Comment by shakedbr** [comment]
Done.
I think you can close this issue.
