### ISSUE TITLE
String attributes containing colon are not quoted

### ISSUE THREAD

**Issue by stefanv** [pydot/pydot#258]
```
import pydot
n = pydot.Node('x', fillcolor='red:yellow')
print(n)
```

Seen:

```
x [fillcolor=red:yellow];
```

Expected:

```
x [fillcolor="red:yellow"];
```

(`dot` won't compile without the value being quoted, complaining of `Error: file.dot: syntax error in line x near ':'`)

This behavior has been confirmed on pydot 2.0.0.dev0.

**Comment by stefanv** [comment]
This was originally reported as https://github.com/networkx/networkx/issues/4663

**Comment by peternowee** [comment]
Thanks for reporting. This is probably very related to pydot/pydot#118 and pydot/pydot#224. Even though those issues are about colons in node/edge names and you are reporting about a colon in a DOT attribute value, both are DOT IDs. Not sure yet if this is a complete duplicate, though, so I suggest we keep this issue open so we can include it as another test case.

All these issues should get fixed as part of the next pydot release (2.0.0) in my opinion, though be prepared that it will still be a while before that gets released. Yesterday @MaxHorwood said in pydot/pydot#224 he would try to work on a PR.

**Comment by stefanv** [comment]
That's great; thanks for the update @peternowee!

**Comment by julianfortune** [comment]
@peternowee Hope you are doing well 😄 I am still interested in finding a solution for this and it looks like you are too! 

Two proposals have occurred to me, and I hope you will indulge me:
1. Change the README so that this line:
    ```python
    my_node = pydot.Node('a', label='Foo')
    ```
    becomes:
    ```python
    my_node = pydot.Node('a', label='"Foo"')
    ```
    and add a little explanation about string literals, so first-time users know how to avoid the problem.

2. Or a massive refactor to use *types* to differentiate string literals directly:
    As an example, if something like this is added to the library:
    ```python
    StringLiteral = namedtuple('StringLiteral', ['value'])  # May want to use dataclass, but this is shorter
    Port = namedtuple('Port', ['something', 'anotherthing'])  # Still don't understand this, sorry
    ...

    Label = Union[StringLiteral, Port, ... etc]  # Don't know what the options are, apologies again
    ```
    Then the user must be explicit about what *type* of label they would like, and it could be error handled:
    ```python
    my_node = pydot.Node('a', label=StringLiteral('Foo'))
    ```
    This would probably involve a lot of work and would make PyDot less of a wrapper, but would enable better error handling and messaging to the user.

I am curious if you or other contributors have proposals for how to address this.

**Comment by laowantong** [comment]
Unfortunately, the workaround function:

```python
def _check_colon_quotes(s):
    # A quick helper function to check if a string has a colon in it
    # and if it is quoted properly with double quotes.
    # refer https://github.com/pydot/pydot/issues/258
    return ":" in s and (s[0] != '"' or s[-1] != '"')
```

... fails when `s` is not a string (e.g., a numeric weight).

**Comment by horvatha** [comment]
@laowantong I can't follow you, where is this workaround function. It's your own?

```python
```

**Comment by laowantong** [comment]
@horvatha Sorry, I should have made myself clearer. This is not my code, but a function of NetworkX:

https://github.com/networkx/networkx/blob/ce692bd3f05900608b829b983838d099b378ca8f/networkx/drawing/nx_pydot.py#L195-L199

I am not sure how it is connected to this project though. My own workaround was to convert to string all the weights of my graph to be able to save it:

```python
    def save(self, stem_or_path):
        # workaround for https://github.com/pydot/pydot/issues/258#issuecomment-1276492779.
        # Convert all edges attributes to strings.
        # The same should be done for nodes attributes, but YAGNI.
        G = deepcopy(self)
        for (x, y, data) in G.edges(data=True):
            for (k, v) in list(data.items()):
                G[x][y][k] = str(v)
        smart_path(stem_or_path).write_text(nx.nx_pydot.to_pydot(G).to_string())
```

**Comment by ferdnyc** [comment]
Honestly, IMHO the right fix is to simply ensure that values are quoted by pydot whenever they need to be. I see this still isn't fixed, looks like `quote_if_needed` needs another upgrade.
