### ISSUE TITLE
Need for pydot 2.0 to support Python 3.5, 3.6?

### ISSUE THREAD

**Issue by peternowee** [pydot/pydot#268]
Pydot 2.0 will drop support for Python 2.7 and 3.4 (see PR pydot/pydot#229). I am still considering if we should drop support for Python 3.5 (EOL since 2020-09-30) as well. And given that the final pydot 2.0 might not get released until after 2021 the question will probably be raised if we should not drop support for Python 3.6 (EOL planned 2021-12) as well.

It is not clear to me how much demand there actually is for continued support of older Python versions.

Supporting older Python versions does not make the support itself cost more time, but it prevents the developers of pydot from using language additions that were introduced in higher Python versions. This is not a big problem by itself either, because problems can still be solved without the latest tools, but it would be a waste if we constrained ourselves for nothing.

So, if you think that you will need pydot 2.0 to support Python 3.5 or 3.6, please make yourself heard now by leaving a comment below to describe your situation (e.g. why you cannot upgrade Python, when that might change, what planned improvements you need from pydot 2.0 that are not in pydot 1.4.2, etc.), so that we can make a more informed decision.

(No need for arguments in favor of dropping Python 3.5/3.6 support. Those are quite clear to me already and can be found all over the Internet. I hope this poll can give us some idea about the pydot users that would be negatively affected. We can discuss if that is a price we are willing to pay after this poll has been open for a while, let's say 3 months.)

**Comment by jarrodmillman** [comment]
FYI, many of the core projects in the scientific Python ecosystem (e.g., numpy, scipy, matplotlib, pandas, networkx, etc.) have already dropped Python 3.6 and will drop 3.7 for any releases after Dec 26, 2021.  For more information, please see:
- https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by lkk7** [comment]
These versions are supported.
Support for Python 2.x has been dropped.
