### ISSUE TITLE
Assertion error -6 (Graphviz on macOS)

### ISSUE THREAD

**Issue by mbprend** [pydot/pydot#270]
I see a similar issue to issue #222 and #203 but with some differences: assertion code is '-6' and I see this message `terminating with uncaught exception of type NSException\n"`

I did follow the steps outlined here: https://github.com/pydot/pydot/issues/203#issuecomment-533164709

I isolated the issue to the dot string:
[offending-dot-string.txt](https://github.com/pydot/pydot/files/6744146/offending-dot-string.txt)

with the following message:
[message.txt](https://github.com/pydot/pydot/files/6744152/message.txt)

I apologize. I am not sure how I to trouble shot the issue.

**Comment by peternowee** [comment]
Hi @mbprend, the log shows that the problem exists when you call Graphviz directly from the command-line already, so this is a Graphviz/Mac issue rather than a pydot issue. I also cannot reproduce this on my Linux machine with either Graphviz 2.40.1 or 2.44.1.

Perhaps related to https://gitlab.com/graphviz/graphviz/-/issues/1320? See pydot/pydot#233 here earlier for a similar case, though that involved a DOT-file with multiple graphs inside, which is not the case for your DOT-file.

If you need more help from me, please post the output of:

```
$ sw_vers
$ dot -V
$ dot -T:
$ dot -v -Tpng:quartz:quartz offending-dot-string.dot >output-quartz-quartz.png
$ echo $?
$ dot -v -Tpng:cairo:quartz offending-dot-string.dot >output-cairo-quartz.png
$ echo $?
$ dot -v -Tpng:cairo:gd offending-dot-string.dot >output-cairo-gd.png
$ echo $?
$ dot -v -Tpng:gd:gd offending-dot-string.dot >output-gd-gd.png
$ echo $?
$ ls -l output*png
$ shasum -a 256 output*png
```

Sooner or later I might still need to point you to the [Graphviz issue tracker](https://gitlab.com/graphviz/graphviz/-/issues) anyway, but then this additional output would probably be useful as well.

If you take this up with Graphviz, please leave a link to that in the comments here for others to follow.

**Comment by mbprend** [comment]
Thank you. 

I did run the set of commands you provided in this [reply](https://github.com/pydot/pydot/issues/270#issuecomment-872084954).

This was the output (below). Just to note, each one of the PNG files is seemingly empty (no image). I will be investigating the issue between Graphviz and MacOS lead. 

```$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
$ dot -V
dot - graphviz version 2.38.0 (20140413.2041)
$ dot -T:
Format: ":" not recognized. Use one of: bmp:quartz:quartz canon:dot:core cgimage:quartz:quartz cmap:map:core cmapx:map:core cmapx_np:map:core dot:dot:core eps:ps:core exr:quartz:quartz fig:fig:core gd:gd:gd gd2:gd:gd gif:quartz:quartz gif:gd:gd gv:dot:core icns:quartz:quartz ico:quartz:quartz imap:map:core imap_np:map:core ismap:map:core jp2:quartz:quartz jpe:quartz:quartz jpe:gd:gd jpeg:quartz:quartz jpeg:gd:gd jpg:quartz:quartz jpg:gd:gd pct:quartz:quartz pdf:quartz:quartz pic:pic:core pict:quartz:quartz plain:dot:core plain-ext:dot:core png:quartz:quartz png:gd:gd pov:pov:core ps:ps:core ps2:ps:core psd:quartz:quartz sgi:quartz:quartz svg:svg:core svgz:svg:core tga:quartz:quartz tif:quartz:quartz tiff:quartz:quartz tk:tk:core vml:vml:core vmlz:vml:core vrml:vrml:gd wbmp:gd:gd xdot:xdot:core xdot1.2:xdot:core xdot1.4:xdot:core
$ dot -v -Tpng:quartz:quartz offending-dot-string.dot >output-quartz-quartz.png
dot - graphviz version 2.38.0 (20140413.2041)
Using render: quartz:quartz
Using device: png:quartz:quartz
libdir = "/Users/mbprend/anaconda3/envs/rmg_env/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
The plugin configuration file:
	/Users/mbprend/anaconda3/envs/rmg_env/lib/graphviz/config6
		was successfully loaded.
    render	:  dot fig gd map pic pov ps quartz svg tk vml vrml xdot
    layout	:  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout	:  textlayout
    device	:  bmp canon cgimage cmap cmapx cmapx_np dot eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4
    loadimage	:  (lib) bmp eps gd gd2 gif jpe jpeg jpg pdf png ps svg xbm
Error: dot: can't open offending-dot-string.dot
$ echo $?
2
$ dot -v -Tpng:cairo:quartz offending-dot-string.dot >output-cairo-quartz.png
dot - graphviz version 2.38.0 (20140413.2041)
Format: "png:cairo:quartz" not recognized. Use one of: png:quartz:quartz png:gd:gd
$ echo $?
1
$ dot -v -Tpng:cairo:gd offending-dot-string.dot >output-cairo-gd.png
dot - graphviz version 2.38.0 (20140413.2041)
Format: "png:cairo:gd" not recognized. Use one of: png:quartz:quartz png:gd:gd
$ echo $?
1
$ dot -v -Tpng:gd:gd offending-dot-string.dot >output-gd-gd.png
dot - graphviz version 2.38.0 (20140413.2041)
libdir = "/Users/mbprend/anaconda3/envs/rmg_env/lib/graphviz"
Warning: Could not load "/Users/mbprend/anaconda3/envs/rmg_env/lib/graphviz/libgvplugin_gd.6.dylib" - file not found
Format: "png:gd:gd" not recognized. Use one of: png:quartz:quartz png:gd:gd
$ echo $?
1
$ ls -l output*png
-rw-r--r--  1 mbprend  staff  0 Jul  6 15:56 output-cairo-gd.png
-rw-r--r--  1 mbprend  staff  0 Jul  6 15:56 output-cairo-quartz.png
-rw-r--r--  1 mbprend  staff  0 Jul  6 15:56 output-gd-gd.png
-rw-r--r--  1 mbprend  staff  0 Jul  6 15:56 output-quartz-quartz.png
$ shasum -a 256 output*png
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  output-cairo-gd.png
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  output-cairo-quartz.png
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  output-gd-gd.png
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  output-quartz-quartz.png```

**Comment by peternowee** [comment]
```
Error: dot: can't open offending-dot-string.dot
```
Was the input file `offending-dot-string.dot` actually present in the working directory?

```
dot - graphviz version 2.38.0 (20140413.2041)
```
This is a very old version of Graphviz. I think one of the first things they might ask you is to check with a more recent version. You probably installed it from [Anaconda's main repository](https://anaconda.org/anaconda/graphviz/files), but you better use the one from the [conda-forge repo](https://anaconda.org/conda-forge/graphviz/files). They have the latest version 2.47.3 (released 2021-06-19). Or use one of the alternative installation methods (from source, MacPorts, Homebrew) listed at https://www.graphviz.org/download/. Hopefully that also solves this strange message:
```
Warning: Could not load "/Users/mbprend/anaconda3/envs/rmg_env/lib/graphviz/libgvplugin_gd.6.dylib" - file not found
Format: "png:gd:gd" not recognized. Use one of: png:quartz:quartz png:gd:gd
```

Then please try the same commands again.

**Comment by peternowee** [comment]
Some old bugs possibly related to `libgvplugin_gd.6.dylib" - file not found`
- https://github.com/biobuilds/biobuilds/issues/5
- https://github.com/ellson/MOTHBALLED-graphviz/issues/1160, from https://github.com/Homebrew/brew/issues/938

But again, upgrading to a more recent version may be better.

**Comment by mbprend** [comment]
Apologies. I added the `offending-dot-string.dot` file to the directory and re-ran the set of commands. The output is here: [output_testing-commands-with-dot-string.txt](https://github.com/pydot/pydot/files/6772866/output_testing-commands-with-dot-string.txt).

In the mean time, I am working to update the version of graphviz. This might take a moment (conda and the time to solve environments). But, once done, I will rerun the set of comments, investigate the issues you shared, and report back. 

Thank you, Peter!

**Comment by mbprend** [comment]
Just a quick update.
I did attempt to update `graphviz` from 2.38.0 to 2.47.3 inside the working conda environment and found a whole list of conflicts.
So, to narrow down if its a macOS or other issue, I created a clean conda environment with just pydot and graphviz added. 
When I run the [commands you shared](https://github.com/pydot/pydot/issues/270#issuecomment-872084954) using `graphviz version 2.38.0`, the output is similar.
When I re-run the commands but with `graphviz version 2.47.3`, I get a diagram I can read!

From this, I think there exists a conflict between `graphviz version 2.38.0` and the version of macOS that are seemingly addressed by updating the `graphviz` package. However, I will need to speak with colleagues about address issues with updating the `graphviz` package inside the working environment.

**Comment by peternowee** [comment]
Yeah, upgrading Graphviz would be best. Otherwise see if you can get 2.38.0 to work with `-Tpng:gd:gd` from the command-line (see https://github.com/pydot/pydot/issues/270#issuecomment-875076423) and then do something like this from Python:

```
try:
    g.write_png("output.png")
except Exception:
    g.write_png("output.png", f="png:gd:gd")
```

(Catching the more generic `Exception` here, because pydot 1.4.2 raises an `AssertionError`, but pydot 2.0 will probably change that.)

However, if you can only get `-Tpng:gd:gd` to work by setting some environment variable, it will be more difficult, because the environment variables that pydot passes to Graphviz are hardcoded, see https://github.com/pydot/pydot/blob/v1.4.2/pydot.py#L124-L128.

**Comment by mbprend** [comment]
After experiencing issues updating GraphViz previously, I reinitialized the update with a better connection using:
`conda install graphviz=2.47.3` inside the conda environment. 

It still took time but conda was better able to resolve necessary updates and I was able to successful run the example script from RMG:
`bash run.sh` in `~/.../RMG/RMG-Py/examples/scripts/generateFluxDiagram`

I also returned to the DOT string in `offending-dot-string.txt` (captured earlier) and was able to generate the Flux diagram.

Thank you so much for your time. I did my best to outline the issue for RMG ([linked here](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2180)) in case an RMG user experiences the same issue.

**Comment by peternowee** [comment]
@mbprend Thanks for reporting back. One question though: From your first comment in https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2180#issue-945703694 it is not 100% clear that the issue got solved by only upgrading to Graphviz 2.47.3, because you mention the combination of Graphviz 2.47.3 and the Graphviz option `-Tpng:gd:gd` solved it, while as I understand from your comments here Graphviz 2.47.3 now also works without the `-T` flag (for example `dot -v offending-dot-string.dot >output-default.png`), right?

**Comment by peternowee** [comment]
Also curious to know what `Using render:` and `Using device:` the `dot` output shows then: Still `quartz:quartz`?

**Comment by mbprend** [comment]
When I remove the `-T` flag like in `dot -v offending-dot-string.dot >output-default.png`:
- The output-default.png file is generated but no image is contained, 
- It also uses 
```
Using render: dot:core
Using device: dot:dot:core
```

For comparison:
- without the `-T` flag:
```
$ dot -v offending-dot-string.dot >output-default.png
dot - graphviz version 2.47.3 (0)
libdir = "/Users/mbprend/anaconda3/envs/rmg_env/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.6.dylib
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
	/Users/<USERNAME>/anaconda3/envs/rmg_env/lib/graphviz/config6
		was successfully loaded.
```
- with the `-Tpng:quartz:quartz` flag
```
$ dot -v -Tpng:quartz:quartz offending-dot-string.dot >output-quartz-quartz.png
dot - graphviz version 2.47.3 (0)
libdir = "/Users/mbprend/anaconda3/envs/rmg_env/lib/graphviz"
Activated plugin library: libgvplugin_quartz.6.dylib
Using render: quartz:quartz
Using device: png:quartz:quartz
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
The plugin configuration file:
	/Users/<USERNAME>/anaconda3/envs/rmg_env/lib/graphviz/config6
		was successfully loaded.
```
The only thing that stands out to me is that the layout is reported in a different order.

**Comment by peternowee** [comment]
Oh, sorry, I should have asked for `-Tpng`, instead of no `-T` at all. So:

    dot -v -Tpng offending-dot-string.dot >output-default.png

That lets Graphviz use its default render/device. I assume that does result in an image, right? Does it use `quartz:quartz` then?

> The only thing that stands out to me is that the layout is reported in a different order.

Yeah, that seems to happen sometimes. See the images in https://github.com/pydot/pydot/issues/213#issuecomment-519875051 for another example (though that even involves differences in different runs using the same settings). Differences between different layout/render engines are probably known, but you would need to check the Graphviz issue tracker.

**Comment by mbprend** [comment]
Sorry, when I do run `dot -v -Tpng offending-dot-string.dot >output-default.png`, it uses (not `quartz:quartz`:
```
Using render: cairo:cairo
Using device: png:cairo:cairo
```

**Comment by peternowee** [comment]
And produces an image?

**Comment by mbprend** [comment]
Yes, sorry. I forgot to say that. It produces an image.

**Comment by peternowee** [comment]
Ok, cool, that means that the upgrade really solved it and I can mention that in issue pydot/pydot#233. Thank you for taking those extra steps! And good luck with your work, let us know if you run into any problems when adding pydot to the mix!
