### ISSUE TITLE
Windows version fails to parse dot format correctly

### ISSUE THREAD

**Issue by amirebrahimi** [pydot/pydot#278]
Some of this is related to #171, but I figured I would make a separate issue since there are more things wrong with parsing.
I'm using pydot 1.4.2. on Windows installed via pip. Comparing to Ubuntu I have no issue with parsing this same graph.

Here's a reduced repro case:
```python
dot = """graph {
0 [label="(0, 0.5, 0.5)", pos="0.5,-0.5!"];
1 [label="(0, 1.5, -0.5)", pos="-0.5,-1.5!"];
0 -- 1 [fontsize=8, label="1.0"];
}"""
pydot.graph_from_dot_data(dot)
```

This produces the following exception:
```
0 [label="(0, 0.5, 0.5)", pos="0.5,-0.5!"];
  ^
Expected '}', found '['  (at char 10), (line:2, col:3)
```

Okay, so related to #171 it's simple enough to do a search and replace of "[" to "{". The problem with making that change is that then tools like `fdp` fail when trying to convert to png (e.g. `plt_image = Image(pdot.create_png(prog="fdp"))`). Anyway, here is the updated sample code.

```python
dot = """graph {
0 {label="(0, 0.5, 0.5)", pos="0.5,-0.5!"};
1 {label="(0, 1.5, -0.5)", pos="-0.5,-1.5!"};
0 -- 1 {fontsize=8, label="1.0"};
}"""
pydot.graph_from_dot_data(dot)
```

but then the following exception happens:

```
0 -- 1 {fontsize=8, label="1.0"};
  ^
Expected '}', found '-'  (at char 160), (line:4, col:3)
```

So, I tried two things, both of which get the code to parse. I haven't been able to verify whether they would still convert to png correctly. The first one is to remove the spaces between the nodes when defining an edge:

```python
dot = """graph {
0 {label="(0, 0.5, 0.5)", pos="0.5,-0.5!"};
1 {label="(0, 1.5, -0.5)", pos="-0.5,-1.5!"};
0--1 {fontsize=8, label="1.0"};
}"""
pydot.graph_from_dot_data(dot)
```

The second one is to wrap the nodes in brackets, but I'm not sure this is correct either:

```python
dot = """graph {
0 {label="(0, 0.5, 0.5)", pos="0.5,-0.5!"};
1 {label="(0, 1.5, -0.5)", pos="-0.5,-1.5!"};
{0} -- {1} {fontsize=8, label="1.0"};
}"""
pydot.graph_from_dot_data(dot)
```

Either way, it seems like parsing on Windows isn't consistent with Ubuntu.

**Comment by peternowee** [comment]
Hi Amir, I don't have much time to look into this in detail, but is there perhaps a difference in the `pyparsing` versions you are using on both platforms? And you are using pydot version 1.4.2 on both platforms, right?

**Comment by amirebrahimi** [comment]
Yes, I'm using pydot 1.4.2 and pyparsing 2.4.7 on both platforms.

**Comment by ferdnyc** [comment]
This appears to already be fixed (possibly the newer `pyparsing` versions now required made the difference), but #325 expands the test suite with a `.dot` file containing the formerly-problem code:

```dot
graph {
0 [label="(0, 0.5, 0.5)", pos="0.5,-0.5!"];
1 [label="(0, 1.5, -0.5)", pos="-0.5,-1.5!"];
0 -- 1 [fontsize=8, label="1.0"];
}
```

...To ensure that it _stays_ fixed.

**Comment by lkk7** [comment]
This was auto-closed by merging https://github.com/pydot/pydot/pull/325, but I'll reopen it if any problem occurs (it shouldn't).
