### ISSUE TITLE
error when writing to file

### ISSUE THREAD

**Issue by roiDaniela** [pydot/pydot#288]
Hello, 

I built a graph and trying to write png but getting the folowing error:
'charmap' codec can't encode character '\u03bb' in position 27: character maps to <undefined>

versions:
windows 10
python 3.8
pydot 1.4.2

graph:
digraph G {
rankdir=LR;
"λ" [fillcolor="#66cc33", peripheries=2, style=filled];
ba [peripheries=2];
baa [peripheries=2];
baba [peripheries=2];
b;
bab;
"λ" -> b  [label=b];
ba -> baa  [label=a];
ba -> bab  [label=b];
b -> ba  [label=a];
bab -> baba  [label=a];
}

Thanks

**Comment by lkk7** [comment]
Sorry for the late answer (you probably don't need it anymore). This project was abandoned, but now it's slowly being revived.

Your graph works fine for me in `pydot`. Your error was certainly related to encoding. Maybe the file wasn't encoded in a standard way.

Closing this as outdated.
Anyone reading this: feel free to tag me if you have any problems
