### ISSUE TITLE
Linebreaks in the .dot file are recognized as a separate node

### ISSUE THREAD

**Issue by JonisK** [pydot/pydot#291]
When I put linebreaks before the curly brace ending a DiGraph, pydot will recognize those as a separate isolated node with the name "\n". Is this expected behavior?
I am using the DOT export of https://arsmasiuk.github.io/qvge/ which unfortunately inserts those linebreaks at the end of each graph.
I am not an expert in graphviz so maybe I am just missing some basic syntax rules.

### Steps to reproduce
Given a file with linebreaks, e.g.
```
digraph G {start -> end;


}
```
and processing that with pydot
```
import pydot
graphs = pydot.graph_from_dot_file("input.dot")
graph = graphs[0]
graph.write_raw('output_raw.dot')
```
results in 
```
digraph G {
start -> end;
"\n\n\n";
}
```
If the last line contains an edge as in `input.dot`, this issue will appear. If the last line states an isolated node like the file `output_raw.dot`, pydot does not interpret the linebreak in front of the closing brace as a new node.

**Comment by InfamyStudio** [comment]
This is happening to me to, really bad! I take in a dot data from another server, parse it and convert it into a graph and bang a "\n" has appeard....

**Comment by lkk7** [comment]
Fixed in latest PRs.
