### ISSUE TITLE
Parameter not used anywhere in code...

### ISSUE THREAD

**Issue by dsantiago** [pydot/pydot#295]
What's the point in this attribute, I could suggest it to be direct parent nodes objects

https://github.com/pydot/pydot/blob/90936e75462c7b0e4bb16d97c1ae7efdf04e895c/src/pydot/core.py#L569

**Comment by dsantiago** [comment]
I can't even evaluate the code almost 1 year later... Many stuff happened, I think... I will just close the issue.

**Comment by ferdnyc** [comment]
It's possible this was meant to be about `parent_node_list` and `parent_edge_list`... _THOSE_ do indeed seem to be completely unused:

```console
$ grep -E 'parent_(node|edge)_list' src/pydot/*.py
src/pydot/core.py:            self.obj_dict["parent_node_list"] = None
src/pydot/core.py:            self.obj_dict["parent_edge_list"] = None
```
