### ISSUE TITLE
A Request For a New Release on PyPI

### ISSUE THREAD

**Issue by hzyrc6011** [pydot/pydot#312]
I am really thankful for such a useful project. However, the latest release `v1.4.2` on PyPI was pushed in 2021, and a large amount of bug fixes and improvements had been done since this release. 

For example, issue #292 will occur in version 1.4.2, but this problem has already been fixed in the master branch.

Could you please push a newer version to PyPI?

**Comment by lkk7** [comment]
Hi @hzyrc6011.
If everything goes well (need some time), I'll try releasing it this evening, so that everything is ready tomorrow.

**Comment by lkk7** [comment]
Done. Report any issues!
