### ISSUE TITLE
Android: not built with triangulation library

### ISSUE THREAD

**Issue by StevanWhite** [pydot/pydot#322]
This is in Termux 0.118.0 on an MT8183 tablet running Android 12, with pydot 2.0.0,
with the attached script "graphviz-problem.py" and dot file "K_5-cross.dot":

`python graphviz-problem.py`
`"dot" with args ['-Tsvg', '/data/data/com.termux/files/usr/tmp/tmpnt44uiqc'] returned code: 1`
(spits out the SVG code)
`Error: remove_overlap: Graphviz not built with triangulation library`

Judging from the Graphviz issues page, this isn't a Graphviz problem, but rather a problem with the dot binary.
[problem_exammple.zip](https://github.com/pydot/pydot/files/14310356/problem_exammple.zip)

On my Linux Mint desktop system, with pydot 1.4.2 from the distro installer, it runs and creates the SVG file. 
I also tried removing the distro pydot, and using pip to install pydot 2.0,0.  The example script still runs properly there.

This appears to be a problem with the dot binary on Android.

**Comment by lkk7** [comment]
Hi @StevanWhite 

If it's a problem with the 'dot' binary, then it's a Graphviz problem, and you should definitely try to create an issue on their site:
https://gitlab.com/graphviz/graphviz/-/issues
Pydot can't handle problems related to the binary being built incorrectly.

**Comment by StevanWhite** [comment]
Hi Łukasz,

OK, I figured something out.  
The "dot" binary came from the distro "graphviz", not from the Python pip-installed packages.

This explains a couple of confusions.  Now, to figure out who to contact about that.
Thanks for the clarification!

**Comment by lkk7** [comment]
I would try posting the problem on the Graphviz issues page with all your details. They'll definitely help you out.

**Comment by StevanWhite** [comment]
https://github.com/termux/termux-packages/issues/19261

**Comment by lkk7** [comment]
Oh, so it was solved in directly in `termux` by installing a missing dependency.
Great then, I can close this for now.
