### ISSUE TITLE
pyclean: py3clean dependency on debpython

### ISSUE THREAD

**Issue by StevanWhite** [pydot/pydot#323]
In the `pyclean` package, the `py3clean` script has a dependency on `debpython`.
This doesn't look right to me, in a Termux script.

Running it fails, though. 

`pip install pyclean`
`py3clean '.'`

Traceback ends with

```
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyclean/py3clean.py", line 32, in <module>
    from debpython import files as dpf
ModuleNotFoundError: No module named 'debpython'
```

Actually, in modern Pythons, py3clean should do the same as pyclean.
It was introduced in some Linux distros to distinguish cleanup of Python 3 from Python 2 directories.

Or... maybe it shouldn't be in the package at all.

**Comment by lkk7** [comment]
Hi @StevanWhite, are you sure you were supposed to post it on pydot's page? 😄 I know you had termux package problems earlier, so...

**Comment by StevanWhite** [comment]
Oh dear.  It's worse than that.  I posted this problem report already this morning on the Termux github, and closed it.
Thinking, this isn't a Termux binary.  And, it's not -- it's from PyPI.  And I mistook your project for whoever is responsible for, I guess, the pyclean package on PyPl  ...

Sorry.
