### ISSUE TITLE
Add example diagrams to readme

### ISSUE THREAD

**Issue by 2br-2b** [pydot/pydot#349]
As someone who's looking for a diagramming software and found this: it might be helpful to put a few screenshots on at least on the Readme. That way, it's easier for people to figure out what the results look like without having to install it

Make one or two simple ones, and at least one complex one to show what the library can do!

Related to #130

**Comment by lkk7** [comment]
Hi @2br-2b,

I understand your point of view, but pydot works entirely on Graphviz. 
To see what pydot can do, you can see what Graphviz can do. 

Still, your issue inspired me to refresh the README.md and I've added a link to the [Graphviz Gallery](https://graphviz.org/gallery/) in the README. 

Thanks and feel free to reach out again if this doesn't satisfy you.

**Comment by 2br-2b** [comment]
Thanks! I was been playing around with this library a bit last night and might have a few more suggestions, but I'll open other issues for those. Thank you!
