### ISSUE TITLE
Why does pydot sort attribute keys?

### ISSUE THREAD

**Issue by ferdnyc** [pydot/pydot#358]
Currently, when `pydot` outputs a list of attributes, it uses `sorted()` to output them in alphabetical order.

But... why?

Since CPython 3.6, and since 3.7 it's part of the language definition, `dict` keys will always be returned in the order they were created. `**kwargs` is also guaranteed to preserve argument order.

Which means that, simply by **not** sorting the attributes, we _could_ output them in the same order they originally appeared, whether they were created by the `dot_parser` or by user code.

That would mean that doing this:
```python
import pydot
from pydot import dot_parser
graph_src = """graph G {
    A [style=dotted, shape=box, color=red]
    B [style=dashed, shape=square]
}"""
g = dot_parser.parse_dot_data(graph_src)[0]
print(g.to_string())
```
Would produce something a lot closer to the original source than this:
```dot
graph G {
A [color=red, shape=box, style=dotted];
B [shape=square, style=dashed];
}
```

**Comment by lkk7** [comment]
That's a great point. Made a PR for this: https://github.com/pydot/pydot/pull/361, feel free to review
