### ISSUE TITLE
Broken to_string() for nodes that contain '^' in 3.0.0

### ISSUE THREAD

**Issue by AlexanderDokuchaev** [pydot/pydot#383]
In case of node name collect `^`, edge saves node names without quotes.

```python
import pydot
graph = pydot.Dot("")
graph.add_node(pydot.Node("Node^A"))
graph.add_node(pydot.Node("Node^B"))
graph.add_edge(pydot.Edge("Node^A", "Node^B"))
data = graph.to_string()
print(data)
n_graph = pydot.graph_from_dot_data(data)
```

### pydot==3.0.0 

```
digraph  {
"Node^A";
"Node^B";
Node^A -> Node^B;
}

Node^A -> Node^B;
    ^
Expected graph_stmt, found '^'  (at char 35), (line:4, col:5)
None
```
### pydot==2.0.0

```
digraph  {
"Node^A";
"Node^B";
"Node^A" -> "Node^B";
}

[<pydot.core.Dot object at 0x7618654bf670>]
```

**Comment by ferdnyc** [comment]
Oh, nope, it's more subtle than that. `quote_id_if_necessary()` _would_ quote `"Node^A"`, but I screwed up the exception logic, so `quote_id_if_necessary("Node^A", unquoted=("node", "graph", "edge"))` **doesn't**.

It was only supposed to except _exact_ matches to the `unquoted` strings, but clearly I did a substring match. Whoops.

Well, easy to fix, at least. Thanks for catching that!

**Comment by lkk7** [comment]
3.0.1 with the bugfix released, thanks @AlexanderDokuchaev for reporting and @ferdnyc for the quick fix
