### ISSUE TITLE
LICENSE file missing in pydot 3 wheels

### ISSUE THREAD

**Issue by radoering** [pydot/pydot#390]
In pydot 2, a `LICENSE` file was included in the `dist-info` folder of the wheel. In pydot 3, this file is missing. This is probably caused by #380 where the license file has been renamed and moved into a `LICENSES` folder. It looks like this folder is not considered when building the wheel.

**Comment by lkk7** [comment]
@radoering Thank you for reporting this and apologies if it's causing any trouble. I'm curious to know how you came across this issue. Did you just notice this randomly or is this important in some workflow?

**Comment by lkk7** [comment]
@ferdnyc
There's an outdated entry in `pyproject.toml`:
```
license = {file = "LICENSE"}
```
But changing it won't affect the released wheel.


Adding this in `setup.cfg`:
```
[metadata]
license_files = LICENSES/*.txt
```
seems to fix the problem (easy to test by running `pip wheel .` and then unpacking the resulting .whl file like a .zip file).
But it results in a MIT.txt file, not a LICENSE file. And with our new licensing system each file could theoretically have a different license. What would be the best way out of this? Is having strictly a "LICENSE" file a standard?

**Comment by ferdnyc** [comment]
@lkk7 Whoops! Didn't even think of that. 

Since the license is a standard one, I believe it should suffice (and probably make the most sense) to simply list the SPDX license expression for the repo, which currently is just "MIT" but in the future might be "MIT and GPL-2.0-or-later and Apache-2.0" (as an example). If the licenses are all OSI-approved standard ones, the name should be sufficient. (Tho it makes sense to include the LICENSES for in the sdist, as well.)

Let me check what the PyPa recommends.

**Comment by ferdnyc** [comment]
Yeah, for example the `reuse-tool` _itself_ has a [`pyproject.toml`](https://github.com/fsfe/reuse-tool/blob/aa5db4412bf62e8b46f42d748f32115beec58263/pyproject.toml) which includes:

### A `[tool.poetry]` section containing an SPDX license expression:

```toml
[tool.poetry]
name = "reuse"
version = "4.0.3"
description = "reuse is a tool for compliance with the REUSE recommendations."
# ...
license = "Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0 AND GPL-3.0-or-later"
readme = "README.md"
```

### A set of corresponding Trove classifiers

```toml
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved",
    "License :: DFSG approved",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]
```
(Hmm, except they're missing CC-BY-SA-4.0. Maybe it doesn't have a Trove identifier yet.)

...I think the Trove classifiers are canonically what PyPi will use to determine the project license(s); a license file or license expression in the metadata is just for downstream users.

### A file `include` expression to package their `LICENSES` dir and `REUSE.toml` config
```toml
include = [
    { path = "src/reuse/locale/**/*.mo", format="wheel" },
    { path = "tests", format = "sdist" },
    { path = "po", format = "sdist" },
    { path = "AUTHORS.rst", format = "sdist" },
    { path = "README.md", format = "sdist" },
    { path = "CHANGELOG.md", format = "sdist" },
    { path = "CONTRIBUTING.md", format = "sdist" },
    { path = ".reuse", format = "sdist" },
    { path = "REUSE.toml", format = "sdist" },
    { path = "LICENSES", format = "sdist" },
    { path = "docs", format = "sdist" },
]
```

**Comment by ferdnyc** [comment]
[Official PyPa docs](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#license-txt) are behind the times and, like GitHub, make terrible assumptions about there being only _one_ license for a given project.

(That's currently _true_ in our case, but that doesn't mean we should fall back into those old patterns of embedding that bad assumption into the configuration itself, as it won't necessarily stay true forever.)

**Comment by ferdnyc** [comment]
Ah, yeah, here we go. PyPa [also says](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license), re: `license` in `pyproject.toml` (emphasis added):

> 
> This can take two forms. You can put your license in a file, typically `LICENSE` or `LICENSE.txt`, and link that file here:
> 
> ```toml
> [project]
> license = {file = "LICENSE"}
> ```
> 
> or you can write the name of the license:
> 
> ```toml
> [project]
> license = {text = "MIT License"}
> ```
> 
> **If you are using a standard, well-known license, it is not necessary to use this field. Instead, you should use one of the [`classifiers`](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#classifiers) starting with `License ::`.** (As a general rule, it is a good idea to use a standard, well-known license, both to avoid confusion and because some organizations avoid software whose license is unapproved.)

**Comment by ferdnyc** [comment]
So, in terms of the Python distribution, what really determines pydot's license is the inclusion of `"License :: OSI Approved :: MIT License"` in its classifiers. Which is present.

We can either just _delete_ the `license` field, or change it to `license = { text = "MIT" }`.

(And I'll open a PR to fix the `MANIFEST.in` so it includes the `REUSE.toml` file.)

**Comment by radoering** [comment]
> I'm curious to know how you came across this issue. Did you just notice this randomly or is this important in some workflow?

We have some internal tooling that checks the license in the `METADATA` **_and_** the availability of license files. If one of both are missing some manual steps are required. I think the `METADATA` is fine due to `"License :: OSI Approved :: MIT License"`. However, the missing license files require some manual steps for us to provide them.

> If the licenses are all OSI-approved standard ones, the name should be sufficient. (Tho it makes sense to include the LICENSES dir in the sdist, as well.)

Not so sure about that. The MIT license in https://github.com/pydot/pydot/blob/main/LICENSES/MIT.txt says

```
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
```

I think this also includes wheels, not just the sdist. You can also put the `LICENSES` folder into `dist-info`.

**Comment by radoering** [comment]
> What would be the best way out of this? Is having strictly a "LICENSE" file a standard?

I'm not aware of a standard, but most libraries put a `LICENSE` / `LICENCE` / `COPYING` file or a `licenses` / `LICENSES` / `license_files` into their `dist-info` folder.

> Yeah, for example the `reuse-tool` [...]

The reuse tool delivers the complete `LICENSES` folder in their `dist-info` of the latest wheel available on PyPI.

**Comment by ferdnyc** [comment]
> The reuse tool delivers the complete `LICENSES` folder in their `dist-info` of the latest wheel available on PyPI.

Makes sense, I just wonder how to _do_ that. `MANIFEST.in` (which already grabs the `LICENSES` folder) takes care of the sdist, but not the wheel.

Ah. Turns out [PEP 639](https://peps.python.org/pep-0639/) proposes to deprecate the `license` field entirely from the metadata, and replace it with `license-expression` and `license-files`. Which makes a ton of sense.

It also appears that `license-files` is [provisionally supported today](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration), so let's try using that.
