### ISSUE TITLE
new line (\n) in node name is causes get_node() method to return empty array (escape issue).

### ISSUE THREAD

**Issue by arik-v** [pydot/pydot#396]
Hi,

There is an issue when the node name contains a new line.
graphviz returns the name escaped, e.g. A\ntest becomes A\\\ntest
but the pydot.Node() constructor in version 3.0.1 does not escape the name.

In 2.0.0 it was handled like this:
[self.obj_dict["name"] = quote_if_necessary(name)](https://github.com/pydot/pydot/blob/85a756ef8f342f9cb369fbccc586d3f03fcc64fb/src/pydot/core.py#L581)

The problem is when getting a node like this (lets assume node name is A\ntest):
     
```
pydot_node = pydot.Node(str_n).get_name()
node = Q.get_node(pydot_node)
```

The node returns empty because the  pydot_node value is: A\ntest (unescaped).
But its saved in the graph (Q) in the obj_dict[nodes] as it is returned from graphviz:  A\\\ntest
That is why the get_node()  returns an empty array.

This is an example code that raises the error. The code I am posting uses networkx but the issue is the inconstancy between node name as returned from the graphviz (escaped) and how its created when using the pydot.Node(str) constructor. 

```
import networkx as nx
import matplotlib.pyplot as plt

G = nx.DiGraph()
G.add_edges_from(
    [('A\ntest', 'B'), ('A\ntest', 'C'), ('D', 'B'), ('E', 'C'), ('E', 'F'),
     ('B', 'H'), ('B', 'G'), ('B', 'F'), ('C', 'G')])

val_map = {'A\ntest': 1.0,
           'D': 0.5714285714285714,
           'H': 0.0}

values = [val_map.get(node, 0.25) for node in G.nodes()]

red_edges = [('A\ntest', 'C'), ('E', 'C')]
edge_colours = ['black' if not edge in red_edges else 'red'
                for edge in G.edges()]
black_edges = [edge for edge in G.edges() if edge not in red_edges]

pos = nx.drawing.nx_pydot.graphviz_layout(G, prog="dot")
nx.draw_networkx_nodes(G, pos, cmap=plt.get_cmap('jet'),
                       node_color=values, node_size=500)
nx.draw_networkx_labels(G, pos)
nx.draw_networkx_edges(G, pos, edgelist=red_edges, edge_color='r', arrows=True)
nx.draw_networkx_edges(G, pos, edgelist=black_edges, arrows=False)
plt.show()
```

**Comment by lkk7** [comment]
Hi @arik-v,

Could you post a more minimalistic example?

```
import pydot

g = pydot.Graph()
n = pydot.Node("a\ntest")
g.add_node(n)

print(g.get_node("a\ntest")[0]) # "a\ntest"
```

The node gets retrieved by the same name it's saved as, is this unexpected behavior?

**Comment by arik-v** [comment]
> Hi @arik-v,
> 
> Could you post a more minimalistic example?
> 
> ```
> import pydot
> 
> g = pydot.Graph()
> n = pydot.Node("a\ntest")
> g.add_node(n)
> 
> print(g.get_node("a\ntest")[0]) # "a\ntest"
> ```
> 
> The node gets retrieved by the same name it's saved as, is this unexpected behavior?

The issue arrises when the node list is desirialized from dot data.
I couldnt get a more minimalized but I this is a more explicit example:
```

import networkx as nx
import matplotlib.pyplot as plt
import pydot

G = nx.DiGraph()
G.add_edges_from(
    [('A\ntest', 'B'), ('A\ntest', 'C'), ('D', 'B'), ('E', 'C'), ('E', 'F'),
     ('B', 'H'), ('B', 'G'), ('B', 'F'), ('C', 'G')])

val_map = {'A\ntest': 1.0,
           'D': 0.5714285714285714,
           'H': 0.0}

values = [val_map.get(node, 0.25) for node in G.nodes()]

# Specify the edges you want here
red_edges = [('A\ntest', 'C'), ('E', 'C')]
edge_colours = ['black' if not edge in red_edges else 'red'
                for edge in G.edges()]
black_edges = [edge for edge in G.edges() if edge not in red_edges]

P = pydot.Dot("", graph_type='digraph', strict=True)
for n, _ in G.nodes(data=True):
    p = pydot.Node(n)
    P.add_node(p)
for u, v, _ in G.edges(data=True):
    u, v = str(u), str(v)
    edge = pydot.Edge(u, v)
    P.add_edge(edge)

# P.create_dot calls the graphviz executable which returns all the \n characters as \\n.
D = str(P.create_dot(prog='dot'), 'utf-8')
Q = pydot.graph_from_dot_data(D)[0]

node_pos = {}

# get positions for nodes
for n in G.nodes():
    str_n = str(n)
    # the part part bellow is the part that fails on 3.0.1 and works on 2.0.0
    # this code worked on 2.0.0 because the Node(..) constructor was escaping \n characters
    pydot_node = pydot.Node(str_n).get_name()
    node = Q.get_node(pydot_node)

    if isinstance(node, list):
        node = node[0]

    pos = node.get_pos()[1:-1]
    if pos is not None:
        xx, yy = pos.split(",")
        node_pos[n] = (float(xx), float(yy))

nx.draw_networkx_nodes(G, node_pos, cmap=plt.get_cmap('jet'),
                       node_color=values, node_size=500)
nx.draw_networkx_labels(G, node_pos)
nx.draw_networkx_edges(G, node_pos, edgelist=red_edges, edge_color='r', arrows=True)
nx.draw_networkx_edges(G, node_pos, edgelist=black_edges, arrows=False)
plt.show()
```

To summarize:
graphviz escapes \\n characters in node name. 
pydot 2.0.0 escapes \\n characters in node name.
pydot 3.0.1 does not escape \\n characters in node name.
hence you can't get node by name when desirialized from graphviz.

**Comment by lkk7** [comment]
I see, sorry for the trouble. I'll check it whenever I'll have free time. (unless someone else checks it first)

**Comment by ferdnyc** [comment]
I think I see the problem.

@arik-v, you're effectively re-creating nodes in that code with this:

```python
>>> import pydot
>>> n = pydot.Node("a\ntest")
>>> pydot.Node(str(n)).get_name()
'"a\\ntest";'
```

Yes, in pydot 3.0.1 that will change the name of the node, because names are now escaped on output, instead of on input. This allows the node name to be retrieved based on the input string, which in pydot 2.0.0 wasn't possible.

In other words, the reason for that change was that in pydot 2.0.0, this _didn't_ work:

```python
>>> g = pydot.Graph()
>>> n = pydot.Node("a\ntest")
>>> g.add_node(n)
>>> g.get_node("a\ntest")
[]
```

You had to look up the Node using its escaped name, which was unintuitive and surprising for many users.

But if you use `str()` on a node, you'll get its escaped definition, and creating a node from its escaped form isn't guaranteed to re-created the same node. (In fact, it's not meant to work at all. Consider this:)

```python
>>> n = pydot.Node("a\ntest", color="red")
>>> str(n)
'"a\\ntest" [color=red];'
>>> n1 = pydot.Node(str(n))
>>> n1.get_name()
'"a\\ntest" [color=red];'
```

That wouldn't have worked correctly in pydot 2.0.0 either, it's only the fact that you were creating nodes _without_ any attributes that let the code you were using work at all. A complete node definition (what you get from running `str(node)` isn't valid input to the `pydot.Node()` constructor.

**Comment by ferdnyc** [comment]
@arik-v 

Oh, wait, no, I see... sorry. `G` is an `nx.DiGraph()`, not a `pydot.Graph()`. My mistake.

I have to look at this in more detail, based on that.

**Comment by lkk7** [comment]
I've been trying to understand what's going on in the NetworkX code here. 
From what I can see, the `nx.drawing.nx_pydot.graphviz_layout` call:

1. Creates a Pydot graph (1) from a NetworkX graph (2)
2. Converts (1) to `.dot` (3)
3. Parses the (3) back to a new Pydot graph (4)
4. Iterates over (2)'s nodes, creates new Pydot nodes (5) from them and then uses (5)'s names to retrieve a node from the (4) graph. The error happens at that point, so what happens after is irrelevant.

I'm not sure where the problem is. There's just so much conversion and something was reliant on the behavior that got fixed (`Node.get_name()` is not escaped anymore). This needs more research.

**Comment by ferdnyc** [comment]
> This method is weirdly complicated – I can't figure out its point. There's just so much conversion

Same, that's where I got stuck, too.

If the code really needs graph elements to have been created with already-quoted names, though (for some reason), there's always the option of calling `quote_id_if_necessary()` **manually** on the argument to `pydot.Node()`. There's a reason the quoting functions _aren't_ private.

I'm not even clear on where exactly it would need to be DONE, in the code provided, but calling `pydot.Node(pydot.quote_id_if_necessary(name))` is a valid option, and will replicate the pydot 2.0 behavior.

**Comment by arik-v** [comment]
what I posed is basically the code of the pydot_layout method from networkx: https://networkx.org/documentation/stable/_modules/networkx/drawing/nx_pydot.html#pydot_layout.

**Comment by lkk7** [comment]
Yeah yeah, that's what we're talking about. Your code is 100% understandable, but the `pydot_layout` from NetworkX seems way too complicated and can probably do what it wants in a simpler way. Maybe I'll create an issue for NetworkX later to see what can be done.

**Comment by lkk7** [comment]
https://github.com/networkx/networkx/issues/7581

**Comment by lkk7** [comment]
This is a short description of the problem:
1. In new versions of Pydot, node names are stored unchanged. 
2. They are quoted/escaped if necessary when output to a `.dot` file. This is to follow the DOT grammar. Example: `Node("a\nb")` must be saved in the .dot file as `"a\nb"` (quoted and escaped), not `a(actual new line)b`.
3. Combining 1. and 2. means that saving a node in `.dot` and reading it back may result in a node with a different name. 
    Example: `Node("a\nb")` -> saved to `.dot` as `"a\nb"` -> read back into a `Node("a\\nb")`.
4. The `nx.drawing.nx_pydot.graphviz_layout` expects this NOT to happen.

I'm preparing a fix.

**Comment by lkk7** [comment]
Let's see how this goes: https://github.com/networkx/networkx/pull/7588
