### ISSUE TITLE
Defaults in dot file seem to cause bad parsing

### ISSUE THREAD

**Issue by mmalcomson** [pydot/pydot#406]
I'm very new to both this project and the graphviz file formats, so apologies if there are obvious errors here.

With the below python file, the output is surprising with both specified edges having the same attributes (even though the defaults change in between edge specification).
There are multiple nodes that have various `None` attributes -- these seem to correspond to where the default statements were.
Moreover in the final PNG, while most of these strange elements are not visible, there is a single blue octagon in the top right hand corner.

```
import pydot

graphtext = r'''digraph testgraph {
    node [color=green];
    node [shape=house];
    initial [label="Initial node"];
    node [color=blue];
    node [shape=octagon];
    second [label="Second node"];
    edge [color=red];
    edge [label="red edge"];
    initial -> second;
    edge [color=blue];
    edge [label="blue edge"];
    second -> initial;
}'''


filegraphs = pydot.graph_from_dot_data(graphtext)
for mygraph in filegraphs:
    print(mygraph.get_name())
    print('  Nodes:')
    for i in mygraph.get_nodes():
        print('    ', i.get_color(), i.get_shape(), i.get_label())
    print('  Edges:')
    for i in mygraph.get_edges():
        print('    ', i.get_color(), i.get_style(), i.get_label())
    filename = f'{mygraph.get_name()}-wrapped.gv.png'
    print(filename)
    mygraph.write_png(filename)

# Notice in the below output that *both* edges are shown as red with the label
# "red edge".
# Moreover, notice that there are nodes with labels that I gave the edges, and
# there are multiple nodes without specific attributes that were not specified.
#
# W.r.t. the final PNG there is an odd extra blue octagon node in the top right.
#
# Output:
#       testgraph
#         Nodes:
#            green house None
#            None house None
#            blue None None
#            None octagon None
#            green house "Initial node"
#            green house "Second node"
#            red house None
#            None None "red edge"
#            blue None None
#            None None "blue edge"
#            green house None
#         Edges:
#            red None "red edge"
#            red None "red edge"
#       testgraph-wrapped.gv.png
```

**Comment by lkk7** [comment]
Hi @mmalcomson, 

Could you specify the `pydot`/`graphviz` version that results in the extra blue octagon node in the top right? I can't reproduce it. 

You may be using an old version of `pydot`. We should probably deprecate all versions `<3.0.0`.
With the latest one, the output of your code is:
```
testgraph
  Nodes:
     green None None
     None house None
     blue None None
     None octagon None
     None None "Initial node"
     None None "Second node"
     red None None
     None None "red edge"
     blue None None
     None None "blue edge"
  Edges:
     None None None
     None None None
```

It looks bad, but doesn't reflect the real state. Let's update the printing part.

```diff
 for mygraph in filegraphs:
     print(mygraph.get_name())
     print('  Nodes:')
-    for i in mygraph.get_nodes():
-        print('    ', i.get_color(), i.get_shape(), i.get_label())
+    for i, n in enumerate(mygraph.get_nodes()):
+        print(f'    {i}: name="{n.get_name()}", attrs={n.get_attributes()}')
     print('  Edges:')
-    for i in mygraph.get_edges():
-        print('    ', i.get_color(), i.get_style(), i.get_label())
+    for i, e in enumerate(mygraph.get_edges()):
+        print(f'    {i}: "{e.get_source()}" -> "{e.get_destination()}"')
```

Now we get:
```
testgraph
  Nodes:
    0: name="node", attrs={'color': 'green'}
    1: name="node", attrs={'shape': 'house'}
    2: name="node", attrs={'color': 'blue'}
    3: name="node", attrs={'shape': 'octagon'}
    4: name="initial", attrs={'label': '"Initial node"'}
    5: name="second", attrs={'label': '"Second node"'}
    6: name="edge", attrs={'color': 'red'}
    7: name="edge", attrs={'label': '"red edge"'}
    8: name="edge", attrs={'color': 'blue'}
    9: name="edge", attrs={'label': '"blue edge"'}
  Edges:
    0: "initial" -> "second"
    1: "second" -> "initial"
```

As you can see, the default node/edge/graph statements are stored as nodes in Pydot.
This allows us to easily output everything the same way it was parsed.
Calling `get_color()` on any node asks it directly if it has a `color=<...>` attribute. It doesn't know about earlier/later default statements.

**Comment by mmalcomson** [comment]
Oh wow -- if versions `<3.0.0` should be deprecated, then the version of pydot in the OS repos I used is *very* old at `1.4.2`.

Thanks for the pointer -- I retried with a version from `pip` and am seeing the same results as you now!
Thanks again!

I'll be honest -- I don't fully understand how the emulating graphviz thing works with that output though -- the defaults appear to be switched to a `blue octagon` before the `initial` node is defined.

That said, the picture I see does show a `green house` as it should be -- so it's not like it's messed anything up, and I have everything I wanted with this new version.

**Comment by lkk7** [comment]
Yeah, the output from `get_nodes()` isn't ordered like specified in the original input  – I don't remember why, but I'll look into it.
However, on actual output to some file or image, the original correct order is preserved.

**Comment by ferdnyc** [comment]
With any version of pydot, the best way to check what's been parsed by `pydot.graph_from_dot_{data,file}()` is to transform it back into graphviz syntax with `.to_string()`. That'll output all of the parsed statements, in the order they're delivered to graphviz. (All statements get a "sequence number" when parsed, and when output they're returned in the same order. It's very possible that `get_nodes()` and `get_edges()` don't return data in sequence order, though.

Using your code, this is what I get with pydot 1.4.2:
```python
>>> # (Define and parse graphtext...)
>>> for mygraph in filegraphs:
...     print(mygraph.to_string())
... 
digraph testgraph {
node [color=green];
node [shape=house];
initial [label="Initial node"];
node [color=blue];
node [shape=octagon];
second [label="Second node"];
edge [color=red];
edge [label="red edge"];
initial -> second;
edge [color=blue];
edge [label="blue edge"];
second -> initial;
"\n";
}
```

...Why there's a final node consisting only of a newline... is probably a bug in the 1.4.2 parser. It doesn't happen with 3.0.1:

```python
>>> for mygraph in filegraphs:
...     print(mygraph.to_string())
... 
digraph testgraph {
node [color=green];
node [shape=house];
initial [label="Initial node"];
node [color=blue];
node [shape=octagon];
second [label="Second node"];
edge [color=red];
edge [label="red edge"];
initial -> second;
edge [color=blue];
edge [label="blue edge"];
second -> initial;
}
```

BTW, you don't _need_ to use default statements unless you actually want to set properties for multiple nodes. Your entire graph code could be rewritten as:

```dot
digraph testgraph {
    initial [label="Initial node", color=green, shape=house];
    second [label="Second node", color=blue, shape=octagon];
    initial -> second [color=red, label="red edge"];
    second -> initial [color=blue, label="blue edge"];
}
```

...And then the sequence order doesn't come into play at all.

**Comment by ferdnyc** [comment]
> Oh wow -- if versions `<3.0.0` should be deprecated, then the version of pydot in the OS repos I used is _very_ old at `1.4.2`.

Probably true, but not because they haven't been updating.

Recent releases have been:
* 1.4.2 - Feb 15, 2021
* 2.0.0 - Dec 30, 2023
* 3.0.0 - Jul 15, 2024
* 3.0.1 - Jul 16, 2024 (to fix my stupid bug in 3.0.0)

So, _most_ distros haven't caught up yet. Even Fedora 40 is on 1.4.2 still.

**Comment by mmalcomson** [comment]
Thank you very much both of you!

FWIW that extra newline in 1.4.2 seems to be the cause of the strange blue octagon that I was seeing in the PNG of my original case.

Thanks again -- closing the issue since it's just questions from my curiosity that I have left now.

**Comment by ferdnyc** [comment]
> FWIW that extra newline in 1.4.2 seems to be the cause of the strange blue octagon that I was seeing in the PNG of my original case.

Yes, that makes sense — the node would be created with the most recent `node` defaults (`color=blue` and `shape=octagon`), with an effectively empty label since it would just consist of a single empty line of text.
