### ISSUE TITLE
Improved branch data in coverage comments

### ISSUE THREAD

**Issue by ferdnyc** [pydot/pydot#424]
Oh!

I thought I was going to have to whip up a PR for this, but turns out I don't need to. It's already ready already.

I recently added support for branch coverage (py-cov-action/python-coverage-comment-action#466) to the GitHub Action we use to report coverage details on the repo and/or PRs, and the new code was released as v3.29 of that project. But since our workflows use the `@v3`-tagged version of the code, which is updated to track each new `v3.××` release, the update became available as soon as it was released, and it already ran the updated code as a post-merge action for #423.

Which means coverage analysis now has a view of branch coverage that aligns with pytest-cov's own, and the coverage percentage displayed in the badge at the top of the [README](../../blob/main/README.md) will no longer annoy me by showing a number that's just _sliiightly_ different from the actual HTML report data (accessible by clicking the badge).

(It's still not _exaaaaactly_ the same, because even though the action's percentage and `coverage.py`'s percentage are now exactly equal, that percentage turns out to be `84.9772382397572` [according to the raw data](https://github.com/pydot/pydot/blob/539ac1433d33fc4543af1e51e5fda62b0c4479ce/data.json), and `coverage.py` rounds that **up** to `85%`, but the action floor-truncates it **down** to `84%`. C'est la vie. If we want them to match, we just need to boost coverage by at least `0.0227617602428%`, but no more than `0.5227617602428%`.)

**Comment by lkk7** [comment]
Great, thank you!
