### ISSUE TITLE
Pydot considers dotted strings like "1.4.0" to be numeric

### ISSUE THREAD

**Issue by ferdnyc** [pydot/pydot#438]
@pktpls wrote:

> Have had the same problem with version numbers in node properties, which end up as e.g. `ipkVersion=1.4.0`, while they should actually be wrapped in quotes

Ooh, that's a different problem. The regular expression used to detect numeric values accepts periods (because, decimal points), but really it should only accept a SINGLE period at most. We'll have to change that from 

```python
re_all_numeric = re.compile(r"^[0-9\.]+$")
```

to something like...

```python
re_all_numeric = re.compile(r"^([0-9]+\.?[0-9]*|[0-9]*\.[0-9]+)$")
```

_Originally posted by @ferdnyc in https://github.com/pydot/pydot/issues/178#issuecomment-2504157116_

**Comment by pktpls** [comment]
Nice, thanks a lot :-)
